---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: environments
  namespace: flux-system
spec:
  interval: 5m
  url: {{ .Values.git.repoUrl }}
  ref:
    branch: {{ .Values.git.mainBranch }}
  secretRef:
    name: git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 10m0s
  path: "./change/me" # will be overridden by overlay in environment
  prune: true
  sourceRef:
    kind: GitRepository
    name: environments
