apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: openmcp-operator
  name: openmcp-operator
  namespace: openmcp-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openmcp-operator
  template:
    metadata:
      labels:
        app: openmcp-operator
    spec:
      initContainers:
        - name: openmcp-init
          image: <openmcp/openmcp-operator>:latest
          args:
            - init
            - --environment=default
            - --config=/etc/secret/openmcp-operator-config/config
          volumeMounts:
            - mountPath: /etc/secret/openmcp-operator-config
              name: openmcp-operator-config
              readOnly: true
      containers:
        - name: openmcp-operator
          image: <openmcp/openmcp-operator>:latest
          args:
            - run
            - --environment=default
            - --config=/etc/secret/openmcp-operator-config/config
          volumeMounts:
            - mountPath: /etc/secret/openmcp-operator-config
              name: openmcp-operator-config
              readOnly: true
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 1000m
              memory: 1024Mi
      volumes:
        - name: openmcp-operator-config
          secret:
            defaultMode: 420
            secretName: openmcp-operator-config
