---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - rbac.yaml
  - deployment.yaml

{{- if .Values.imagePullSecrets }}
patches:
  - target:
      kind: Deployment
    patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: this_value_is_ignored
      spec:
        template:
          spec:
            imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 14 }}
{{- end }}

