name: Lint YAML and Kustomization

on:
  pull_request:
    paths:
      - "templates/**.yaml"
      - "templates/**.yml"
      - "templates/**/kustomization.yaml"
  push:
    paths:
      - "templates/**.yaml"
      - "templates/**.yml"
      - "templates/**/kustomization.yaml"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install yamllint
        run: pip install yamllint

      - name: Lint YAML files
        run: yamllint templates/
