name: Lint YAML and Kustomization

on:
  pull_request:
    paths:
      - "templates/**.yaml"
      - "templates/**.yml"
  push:
    paths:
      - "templates/**.yaml"
      - "templates/**.yml"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with:
          python-version: "3.x"

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run lint task
        run: task lint
